version: "3.8"

services:
  # Put Mailcow UI behind Coolify's Traefik (HTTPS handled by Coolify)
  nginx-mailcow:
    # Remove host 80/443 binds from base compose; Coolify/Traefik will route to container:80
    ports: []

  # Sender Rewriting Scheme (SRS) daemon for forwarding
  postsrsd:
    image: ghcr.io/fphammerle/postsrsd:1.0.0
    restart: unless-stopped
    networks:
      - mailcow-network
    volumes:
      - ./data/conf/postsrsd/postsrsd.conf:/etc/postsrsd/postsrsd.conf:ro
      - ./data/conf/postsrsd/secret:/etc/postsrsd.secret:ro

  # Make sure Postfix starts after postsrsd
  postfix-mailcow:
    depends_on:
      - postsrsd
